#-------------------------------
# General Site Settings

menu:
#- {name: 'Box', url: ''}
- {name: 'BLOG', link: 'https://kei-kju.tumblr.com'}
- {name: 'INFO', url: 'pages/about.html'}
- {name: 'SHOP', url: 'pages/shop.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal site powered by Jekyll and GitHub Pages '
  #rel-author: 'https://plus.google.com/u/0/#'
  #rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'asdfkjg'

#-------------------------------
# About Section

about: >

  I draw. Here be my stuff. Please enjoy.



contact: >
  # Contact


#-------------------------------
# Work Section

projects:
#- {name: 'sketch', folder: 'sketch', file: 'projects/sketch.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/sqkaas'}
- {icon: 'instagram', link: 'https://www.instagram.com/keikju/'}
- {icon: 'github', link: 'https://github.com/keikju'}
- {icon: 'twitch', link: 'https://www.twitch.tv/acheesewedge'}
- {icon: 'tumblr', link: 'https://kei-kju.tumblr.com'}
- {icon: 'envelope', link: 'mailto:keikju@pm.me'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
